### ISSUE TITLE
Mettre à jour le readme pour préciser la dernière version stable

### ISSUE THREAD

**Issue by phacks** [theodo/theodo-stack-generator#102]
En suivant les instructions du README, j'ai installé la branche `master` qui n'était pas du tout stable.

Il faudrait indiquer la dernière versions stable dans le README.

**Comment by benja-M-1** [comment]
@phacks quels étaient les problèmes que tu as rencontré ?

**Comment by phacks** [comment]
@benja-M-1 J'en ai parlé vite fait à @JusteLeblanc mais j'en ai corrigé 5 (toutes bloquantes) dans cette pr #101, et je pense qu'il en reste encore
