### ISSUE TITLE
Comment je mets à jour theodo-stack-generator ?

### ISSUE THREAD

**Issue by jbeurel** [theodo/theodo-stack-generator#104]
Salut,

Je créé un nouveau projet. J'ai déjà Theodo Stack Generator sur mon laptop.

- C'est quoi la procédure la plus courte pour mettre à jour TSG ?

**Comment by benja-M-1** [comment]
Tu mets à jour ton repository git et ensuite :

```bash
$ cd theodo-stack-generator && yarn && npm link && cd ../
$ npm install -g theodo-stack-generator
```

**Comment by jbeurel** [comment]
Je ne pense pas que ce soit suffisant. Après le npm link, le dossier local fait partie des repo npm. Du coup, il faut faire un git pull, puis un npm update -g theodo-stack-generator.

Si c'est bien ça, j'ai fait un PR de MAJ de la doc -> https://github.com/theodo/theodo-stack-generator/pull/139

**Comment by benja-M-1** [comment]
Comme je viens de te montrer le npm link fait un lien symbolique donc l'update sert à priori à rien

**Comment by tcheymol** [comment]
Ça a été rajouté dans la doc, je close l'issue
