### ISSUE TITLE
Il y a un conflit à la création du projet react sur src/index.css

### ISSUE THREAD

**Issue by jbeurel** [theodo/theodo-stack-generator#105]
Voici mes réponses à Yo
![image](https://user-images.githubusercontent.com/1665948/37665747-3adced18-2c5e-11e8-9cb3-47d369c63106.png)
Voici le message d'erreur
![image](https://user-images.githubusercontent.com/1665948/37665693-1f36b77e-2c5e-11e8-9c05-5a65cbe2071b.png)

**Comment by benja-M-1** [comment]
@jbeurel tu sais quel était le conflit dans le fichier ?

**Comment by jbeurel** [comment]
Je n'ai plus le problème. J'ai l'impression que ton commit a résolu le problème
