### ISSUE TITLE
[Symfony 4] Utiliser dotenv pour la gestion des variables d'environnement

### ISSUE THREAD

**Issue by JusteLeblanc** [theodo/theodo-stack-generator#112]
- [x] Mettre à jour le .env avec l'ip du serveur en trusted proxies
- [ ] Documenter la création du .env sur le staging et la prod

**Comment by benja-M-1** [comment]
@JusteLeblanc tu devrais lire http://fabien.potencier.org/symfony4-best-practices.html#environment-variables

**Comment by benja-M-1** [comment]
On clos cette issue. Aujourd'hui le déploiement génère le .env à partir du dist.
