### ISSUE TITLE
Getting rid of Immutable

### ISSUE THREAD

**Issue by williamdclt** [theodo/theodo-stack-generator#117]
One of the main differences between FR and UK React boilerplates is the use of Immutable. We are not using it in the UK, and nobody here seems keen on using it on a project (even for people having used it before).

Currently, that's one of the blockers for merging the UK and FR boilerplates.

The arguments are:
- It is unnecessary, we don't need ImmutableJS to write immutable code (and the code we write *is* immutable, that's not just theoretical)
- It's not nicer syntaxically if using ES6 (all projects do), thanks to rest/spread
- It's a cognitive overhead: code is harder to write and to read
- We end up with a mix of JS objects and Immutable objects
  - If correctly handled, that's a lot of `fromJS` and `toJS` everywhere
  - If not correctly handled, that's a big source of bugs
  - In any case that's again a major cognitive overhead
- It's one more barrier for newcomers
- It can impact perfs because of `toJS` forcing rerendering
  - It is avoidable... but cognitive overhead again
- Worse autocompletion in IDEs/editors than with JS objects
- Quite heavy in the bundle

The only pro I see is enforcing immutability, which seems unnecessary as we do write immutable code.

@JeremD @lechinoix

**Comment by benja-M-1** [comment]
The latest news I have from @jbeurel is that @JeremD discoverd that Immutable is not a good choice. He will publish an article to explain why and then remove Immutable from the stack :) Should be done by 20/04 !

**Comment by williamdclt** [comment]
👍

**Comment by williamdclt** [comment]
Done by @JeremD in https://github.com/theodo/theodo-stack-generator/pull/126
