### ISSUE TITLE
Flow pro and con

### ISSUE THREAD

**Issue by williamdclt** [theodo/theodo-stack-generator#118]
It seems that it became a standard in FR project to use Flow. What are the arguments? Pros and con? 

Today that's one of the blockers that prevents merging the UK and FR boilerplates

@lechinoix @tcheymol

**Comment by tcheymol** [comment]
@williamdclt Flow helps developpers a lot 

- Code faster with IDE autocompletion
- Understand the code faster
- Check a lot of edge cases (bye bye "can not get property 'truc' of undefined"), so reduces the bugs amount
- Helps in writing tests scenarios

**Comment by williamdclt** [comment]
@tcheymol  I have no argument against, there's an ongoing discussion in the UK about using Flow. I might come back to you if it ends up being KO'd. Worst case scenario, we maintain an unflowed.

I'll close for now
