### ISSUE TITLE
Change ".component" and ".container" extensions

### ISSUE THREAD

**Issue by williamdclt** [theodo/theodo-stack-generator#119]
The current naming convention for React components in this boilerplate is to name them `Foo.component.js` (for presentationals) and `Foo.containers.js` (for containers).

In the UK, our convention is to name them respectively `Foo.js` and `Foo.wrap.js`. The advantages are:
- Shorter name for same quantity of information
  - Both "component" and "container" are fairly long words, that clutter the editor tabs very quick
- Better differenciation
  - "container" and "component" are fairly similar words (same first syllable, same number of syllables, same number of letters). That's not ideal to differenciate them at a glance.
- Better terminology
  - "component" is not a good terminology: a container is also a component. Dan Abramov use the word "presentational", I'm not sure how we ended up using "component" for those.
  - "container" is commonly accepted as "a component that is connected to the redux state". "wrap" is more generic: we use those file for various higher-order components in the UK, not only `connect()` (in my current project, we have wrappers that stack more than 10 HoC for example).
- Better search in IDE and editors
  - "component" and "container" start with the same first 2 letters, and those letters are fairly common
  - the unusual "w" in "wrap" allows to search for the file more easily (looking for "foow" is easier and will yield better results than looking for "foocon")

All in all, the functionality is the same obviously, but it's more comfortable and integrates better in an editor (and as we spend several hours a day in our editor, that's welcomed!)

**Comment by benja-M-1** [comment]
> "wrap" is more generic: we use those file for various higher-order components in the UK, not only connect() (in my current project, we have wrappers that stack more than 10 HoC for example).

@williamdclt can you paste samples of wrappers that stack many HoC?

**Comment by williamdclt** [comment]
```
import { reduxForm } from 'redux-form';
import { connect } from 'react-redux';
import { getInitialValues, isReadOnly } from 'services/audit.service';
import {
  withProps,
  lifecycle,
  setDisplayName,
  compose,
  withSites,
  withTemplates,
  withAuditorProfiles,
} from 'hoc';
import { injectIntl } from 'react-intl';
import { templatesToOptions } from 'services/template.service';
import { fetchTemplateVersion } from 'redux/audit/template.actions';
import { getAuditFormTemplateValue } from 'redux/audit/audit.selectors';
import { getTemplateVersion } from 'redux/audit/template.selectors';
import AuditForm from './AuditForm';

const mapStateToProps = (state, props) => ({
  templateValue: getAuditFormTemplateValue(state, props),
  templateVersion: getTemplateVersion(state, props),
});

const mapDispatchToProps = dispatch => ({
  fetchTemplate: versionId => dispatch(fetchTemplateVersion.request(versionId)),
});

const AuditFormWrapper = compose(
  setDisplayName('AuditFormWrapper'),
  injectIntl,
  connect(mapStateToProps, mapDispatchToProps),
  withProps(({ audit, templateVersion }) => ({
    initialValues: getInitialValues(audit, templateVersion),
    readOnly: isReadOnly(audit),
    onSubmitFail: () => window.scrollTo(0, 0),
  })),
  reduxForm({ enableReinitialize: true }),
  withSites(),
  withTemplates(),
  withAuditorProfiles(),
  withProps(props => ({
    templateChoices: templatesToOptions(props.templates),
  })),
  lifecycle({
    componentDidMount() {
      if (this.props.audit && this.props.templateValue) {
        this.props.fetchTemplate(this.props.templateValue);
      }
    },
    componentWillReceiveProps(nextProps) {
      if (nextProps.templateValue !== this.props.templateValue) {
        this.props.fetchTemplate(nextProps.templateValue);
      }
    },
  }),
)(AuditForm);

export default AuditFormWrapper;

```

**Comment by tcheymol** [comment]
@williamdclt That seems good, I have no reluctance

**Comment by williamdclt** [comment]
Done

**Comment by jbeurel** [comment]
Hi @williamdclt 

Beau boulot. Tes explications et tes exemples sont très clairs. Est-ce que tu peux mettre à jour le standard M33 en suivant ces nouvelles conventions de nommage ? -> http://blog.m33.network/2017/11/react-component/

**Comment by williamdclt** [comment]
@jbeurel Done!
