### ISSUE TITLE
React: move tests to subfolders

### ISSUE THREAD

**Issue by williamdclt** [theodo/theodo-stack-generator#120]
The React tests in this boilerplate are at the same level as the code:
```
components/
  ┗ Foo/
    ┗ Foo.component.js
    ┗ Foo.component.test.js
    ┗ Foo.container.js
    ┗ Foo.container.test.js
    ┗ Foo.snapshot.test.js
    ┗ index.js
```

This clutters the component folder and makes it harder to find instantly what you're looking for.

A more common pattern is to put the tests in a subfolder:

```
components/
  ┗ Foo/
    ┗ tests/
      ┗ Foo.container.test.js
      ┗ Foo.snapshot.test.js
      ┗ Foo.component.test.js
    ┗ Foo.component.js
    ┗ Foo.container.js
    ┗ index.js
```

Any particular reason this isn't the case here? @lechinoix @georgesbiaux

**Comment by georgesbiaux** [comment]
@williamdclt No particular reason for me. I agree to move the tests files in a dedicated folder :)

I assign the issue to myself

**Comment by tcheymol** [comment]
@williamdclt Ok for me. You wanna to it ?

**Comment by williamdclt** [comment]
Done
