### ISSUE TITLE
Is the example app useful?

### ISSUE THREAD

**Issue by williamdclt** [theodo/theodo-stack-generator#124]
Is anyone actually using the example app?

The code is sprinkled with `<% if (exampleRequired) { %>` tags. That makes the generator quite hard to maintain, and hard to test.

We could have a separate repo with a sample app if having an example seem necessary. Downside would be that it would require to maintain both repos in parallel.

This is just an idea, not a strong opinion. If you have an example of someone that used it and found valuable, that's fine with me!

**Comment by benja-M-1** [comment]
I don't like the idea to have a separate repository for the examples. 

Maybe we could dynamically add the examples components and pages in the code instead. @williamdclt @tcheymol @georgesbiaux @ghamaide do you any existing solution that could do that?

**Comment by williamdclt** [comment]
Before looking for how to handle the example app: has it ever been used by anyone?

**Comment by benja-M-1** [comment]
Good point, I do not know! I will ask on workplace. BTW it makes me think that we do not have any feedback on the generator usage. We could add something like this: https://github.com/yeoman/insight

**Comment by tcheymol** [comment]
@williamdclt The example is here to demonstrate good practices in React and to drive a clean maintainable, and m33-shared architecture, so we need this for new project.
