### ISSUE TITLE
Do not use `Container` for the name of the generated styled.div around a component

### ISSUE THREAD

**Issue by foucdeg** [theodo/theodo-stack-generator#134]
It's confusing :/

**Comment by williamdclt** [comment]
Agreed.
And I'm not sure the architecture here really makes sense? I'm expecting the `Foo.style.js` to import and wrap `Foo.component.js` with some style, not `Foo.component` to wrap itself. There's no reason for the `.component` to be aware of styling, and it makes it less reusable

**Comment by foucdeg** [comment]
@williamdclt a downside of that would be that you have no control over where to use the styled.div : it will systematically create a <div> around your component

**Comment by williamdclt** [comment]
I'm not used to styled so I'm really not the best to judge of that, but it seem to make sense to me to systematically create the `div` around the component. It doesn't seem a good pratice to have this `Container` somewhere inside the component.

But then once again, I've never actually used styled so...

**Comment by foucdeg** [comment]
I'd rather control where actual DOM is created.

**Comment by benja-M-1** [comment]
@foucdeg to better understand your point, I need an example of what is wrong to you and what it should be. Can you do that please?

**Comment by foucdeg** [comment]
@benja-M-1 here's the generated code for a PureComponent using StyledComponents:

```
import React, { PureComponent } from 'react';

import { Container } from './TestComponent.style';

type Props = {
};

class TestComponent extends PureComponent<Props> {
  render() {
    return (
      <Container>
      </Container>
    );
  }
}

export default TestComponent;
```

I just want the styled div `Container` to be called something else, because people might think that it refers to a Redux container, although it's a styled div. Let's avoid having one name for two completely different things.

**Comment by foucdeg** [comment]
as seen with @Kui-kui : 
- in {{ component }}.style.js, name the div `Styled` with the component name and make it default export
- in {{ component }}.component.js, import it as `Style`

**Comment by benja-M-1** [comment]
@foucdeg would you mind submit a PR?

**Comment by foucdeg** [comment]
@benja-M-1 sure !

**Comment by foucdeg** [comment]
@benja-M-1 @williamdclt @Kui-kui I just found out that the issue has already been mitigated by [this commit](https://github.com/theodo/theodo-stack-generator/commit/8992fe92c5dcfcd256495a1e8e805a894475d7ca#diff-be1218dead5ec230a4053c985243c477) where Redux containers were renamed wrappers. There is no longer a conflict on the name "Container".

However, I still feel that "Style" and "StyledTodoList" are better styled component names than Containers, so I'll go ahead with the PR.

**Comment by benja-M-1** [comment]
@foucdeg Thanks, I merged your PR :)
