### ISSUE TITLE
API Platform generator does not work

### ISSUE THREAD

**Issue by jbeurel** [theodo/theodo-stack-generator#140]
Voici ce que j'ai demandé au générateur
![image](https://user-images.githubusercontent.com/1665948/39546368-74624c78-4e54-11e8-8d52-c6e0dd8eb599.png)

Et voici le contenu du répertoire.
![image](https://user-images.githubusercontent.com/1665948/39546377-7cfc5e00-4e54-11e8-86e3-554355fda6b8.png)

Je n'ai pas de dossier `server`. J'ai loupé quelque chose ?

ping @benja-M-1 @JusteLeblanc @ghamaide @georgesbiaux

**Comment by JusteLeblanc** [comment]
@jbeurel le générateur APIPlatform permet de : 
- générer le provisionning pour avoir une VM PHP7 avec Nginx configuré 
- générer une doc pour installer un projet Symfony en quelques lignes de commande shell (Readme). C'est en suivant cette doc que tu auras un dossier api ou server
