### ISSUE TITLE
cannot use component generator (plop) if no folder 'pages'

### ISSUE THREAD

**Issue by YuLingCheng** [theodo/theodo-stack-generator#144]
![image](https://user-images.githubusercontent.com/7447041/40713426-2f5624da-6400-11e8-866f-7916fb69f732.png)

**Comment by jbeurel** [comment]
Salut @marcenacp . Yuling fait un client chat en React. Elle n'a pas de répertoire "pages", du coup, elle ne peut pas utiliser le générateur de composant. Tu crois que tu peux gérer pour que le répertoire "pages" soit optionnel ?

**Comment by marcenacp** [comment]
@YuLingCheng @jbeurel There is a quick PR for that: https://github.com/theodo/theodo-stack-generator/pull/146

**Comment by marcenacp** [comment]
@YuLingCheng Can you confirm it solved your issue?
(You can copy `theodo-stack-generator/generators/react/templates/scripts/generators/` in your project `scripts/generators`.)

**Comment by YuLingCheng** [comment]
Thanks @marcenacp !

**Comment by YuLingCheng** [comment]
@marcenacp perfect thanks!
