### ISSUE TITLE
I have an ansible based generator

### ISSUE THREAD

**Issue by Miniplop** [theodo/theodo-stack-generator#16]
### The proposed architecture:

Yeoman only creates a playbook with the roles corresponding to the user choices.
You run ansible and the whole stack is created.

### Plan d'une install

0. Lancer Yeoman pour générer le Vagrantfile et le playbook
1. Installer Vagrant
2. Le playbook installe les logiciels (nginx, php, node, etc)
3. Le playbook copie les bons fichiers (react, angular, loopback, symfony, etc)
4. Le playbook installe les dépendances

### Plan de la migration

1. Faire un playbook pour la stack react + loopback
2. Générer le playbook du 1 via Yeoman
2. Faire un playbook pour la stack react + symfony
4. Yeoman gère les 2 playbooks

**Comment by cRicateau** [comment]
@Miniplop I am not sure why you would want to use ansible instead of javascript to handle all of this, what is the problem with yeoman ?

**Comment by benja-M-1** [comment]
@Miniplop je comprends pas ce que tu proposes. C'est toujours d'actualité ? Sinon tu peux fermer l'issue stp ?
