### ISSUE TITLE
Vagrant base image is outdated

### ISSUE THREAD

**Issue by clementhannicq** [theodo/theodo-stack-generator#173]
```
==> default: A newer version of the box 'ubuntu/xenial64' for provider 'virtualbox' is
==> default: available! You currently have version '20180504.0.0'. The latest is version
==> default: '20180824.0.0'. Run `vagrant box update` to update.
```

**Comment by benja-M-1** [comment]
The only information the generator provides to Vagrant is the box name: https://github.com/theodo/theodo-stack-generator/blob/master/generators/server/templates/Vagrantfile#L2

@clementhannicq correct me if I am wrong, the box management must be done on the host machine. So you have to upgrade it on your own with the command Vagrant gave you.
