### ISSUE TITLE
Why Node 9.5 ?

### ISSUE THREAD

**Issue by clementhannicq** [theodo/theodo-stack-generator#174]
@tcheymol we are using node 9.5, this is neither a LTS version nor the lastest version.

Why specify the node version at all, actually? I'm running the generator with node 10.9 and I'm not encountering any issue

**Comment by ghamaide** [comment]
@clementhannicq @tcheymol switched to v10.9.0 on master in this PR #181 .
I'll handle switching the README.md to Node v10.9.

**Comment by ghamaide** [comment]
PR: https://github.com/theodo/theodo-stack-generator/pull/184
