### ISSUE TITLE
Can't build the project in production mode with npm

### ISSUE THREAD

**Issue by AleBlondin** [theodo/theodo-stack-generator#199]
When running `npm install --production`, eslint is not installed. Afterwards `npm build --production` throws an error because eslint is not installed.

I looked up the error quickly and I found this issue : https://github.com/facebook/create-react-app/pull/3771 that warns about adding eslint as a devDependency when using react-scripts.

For info I am the first to face this issue because I changed on my project the capistrano deployment script so it uses npm instead of yarn

**Comment by AleBlondin** [comment]
Also linked with this issue about npm against yarn usage: https://github.com/theodo/theodo-stack-generator/issues/183

**Comment by AleBlondin** [comment]
![image](https://user-images.githubusercontent.com/25102531/45354556-2b51e080-b5be-11e8-88d1-5478c34342d3.png)

**Comment by AleBlondin** [comment]
package.json:

```
  "dependencies": {
    "@api-platform/admin": "^0.5.0",
    "@babel/runtime": "7.0.0-beta.55",
    "lodash": "^4.17.10",
    "plop": "^1.9.1",
    "react": "^16.2.0",
    "react-admin": "~2.2.0",
    "react-dom": "^16.2.0",
    "react-redux": "^5.0.7",
    "react-router-dom": "^4.2.2",
    "react-scripts": "^1.1.1",
    "react-test-renderer": "^16.2.0",
    "redux": "^3.7.2",
    "redux-saga": "^0.16.0",
    "reselect": "^3.0.1",
    "source-map-explorer": "^1.5.0",
    "styled-components": "3.1.6",
    "superagent": "^3.8.3"
  },
  "devDependencies": {
    "babel-eslint": "^8.2.1",
    "cross-env": "^5.2.0",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "enzyme-to-json": "^3.3.0",
    "eslint": "^4.18.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-flowtype": "^2.44.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jest": "^21.12.1",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-mysticatea": "^4.2.4",
    "eslint-plugin-prefer-object-spread": "^1.2.1",
    "eslint-plugin-prettier": "^2.6.0",
    "eslint-plugin-react": "^7.6.1",
    "flow-bin": "^0.68.0",
    "flow-coverage-report": "^0.4.1",
    "flow-typed": "^2.3.0",
    "husky": "^0.14.3",
    "jest-cli": "^20.0.4",
    "lint-staged": "^7.1.2",
    "nsp": "^3.2.1",
    "prettier": "^1.10.2"
  },
```

**Comment by benja-M-1** [comment]
I also have an error but I have another error on the same file.

I tried to generate a new project with create-react-app, install the same version of eslint as you, installing and building with --production works fine.

This, I don't think it is related to eslint. But I can't figure out why it fails for the moment...
