### ISSUE TITLE
Do not create client/ or server/ subdirectories when generating a client only or a server only

### ISSUE THREAD

**Issue by foucdeg** [theodo/theodo-stack-generator#41]
I generated only a client, and it was generated in the `client/` subdirectory of my project. There's not much point of a `client/` subdirectory if you just have the client. I ended up moving everything up one level.

**Comment by benja-M-1** [comment]
@foucdeg could you please do a PR?

**Comment by foucdeg** [comment]
@benja-M-1 Sure, but I know nothing about yeoman generators. I'll look into it.

**Comment by cRicateau** [comment]
#67
