### ISSUE TITLE
Split generators in react / provisioning / deployment / server

### ISSUE THREAD

**Issue by benja-M-1** [theodo/theodo-stack-generator#52]
Having a standalone client app generator and server app generator.
Do not generate a client directory when no backend is used #41

**Comment by jbeurel** [comment]
"Do not generate a client directory when no backend is used" +1

"Having a standalone client generator and server generator." Why ?

**Comment by benja-M-1** [comment]
I updated the description. We may want to generate only the client app without backend. Moving them in different generators is a way to decouple the two in the code. There may be other options :)

**Comment by jbeurel** [comment]
@benja-M-1 Je ne comprends toujours pas le cas d'usage :-/

**Comment by cRicateau** [comment]
#67
