### ISSUE TITLE
Use Fansible provisioning

### ISSUE THREAD

**Issue by benja-M-1** [theodo/theodo-stack-generator#57]
@MaximeThoonsen would you like to update fansible and integrate it in here?

**Comment by MaximeThoonsen** [comment]
@benja-M-1 I can help if there are problem but I think the roles here are fine. Next bug update will be for the next Ubuntu LTS

**Comment by benja-M-1** [comment]
I mean I would like we do not reinvent the wheel here and reuse what you've done on Fansible instead.

**Comment by MaximeThoonsen** [comment]
@benja-M-1 it's too late
