### ISSUE TITLE
Add a plopjs generator to create components

### ISSUE THREAD

**Issue by cRicateau** [theodo/theodo-stack-generator#59]

**Comment by jbeurel** [comment]
Salut @cRicateau 

C'est bien avec toi que j'ai eu la conversation par téléphone sur Plopjs ? Tu m'avais dis que ça ne valait pas le coup et que c''était mieux de faire une refacto plutôt que je générer du code.

Ca a changé ? L'approche est différente ?

**Comment by marcenacp** [comment]
#66

**Comment by cRicateau** [comment]
@jbeurel Oui on en avait parlé. Je l'avait compris au début comme un moyen de remplacer yeoman et/ou un moyen de générer des modules de l'appli tel qu'un CRUD par exemple.

Après démo d'un cas d'usage par @marcenacp et le retour d'XP sur Saham, je vois aujourd'hui un vrai valeur. L'objectif est de pouvoir générer son component react en une command, au lieu de devoir créer un fichier, copier-coller le contenu d'un autre  composant, mettre a jour les proptypes etc...

**Comment by cRicateau** [comment]
#66
