### ISSUE TITLE
Create an alias to avoid relative import

### ISSUE THREAD

**Issue by Miniplop** [theodo/theodo-stack-generator#6]
To avoid this :
![image](https://user-images.githubusercontent.com/15800180/29005479-90177c78-7adc-11e7-9287-1ba91344c6ce.png)

It's a good practice to have an 'src' alias in the webpack config 
=> Vue cli make the change here => https://github.com/vuejs/vue-cli/commit/e98cc81acb0a6a244db6de9198d00d1621616837

To do so we can run 'yarn eject' => then add this line in the webpack config alias part:
`'{MyAppName}': path.resolve('src')`

@cRicateau How can we add this behavior in the generator, I'm a super noob in yeoman ? :)

**Comment by cRicateau** [comment]
@Miniplop have you tried https://github.com/facebookincubator/create-react-app/issues/2188 ?

**Comment by Miniplop** [comment]
@cRicateau Not yet, I will tomorow :)

**Comment by Miniplop** [comment]
@cRicateau I didn't test yet, I schedule this on sunday :)

**Comment by cRicateau** [comment]
@Miniplop 
I tried 
```
NODE_PATH=src
```
in your client/.env file for this.

It worked, but then it breaks the linter for the "import/no-extraneous-dependencies" rule... Maybe it could be added in the doc to explain how to do it ?

**Comment by cRicateau** [comment]
@tcheymol #44

**Comment by benja-M-1** [comment]
@cRicateau @Miniplop what is the status of this issue?

**Comment by cRicateau** [comment]
#44 closes this issue
