### ISSUE TITLE
Add "withRouter" on all pages - waiting for react-router-redux v5 stable release

### ISSUE THREAD

**Issue by cRicateau** [theodo/theodo-stack-generator#72]
Otherwise we dont understand how history is injected

**Comment by ghamaide** [comment]
@tcheymol @benja-M-1 we should use react-router-redux instead rather no ?

**Comment by benja-M-1** [comment]
@lechinoix ?

**Comment by williamdclt** [comment]
@ghamaide Redux 16 is only compatible with react-router 4, which is only compatible with react-router-redux 5 *alpha*. Using alpha packages is a bad idea, and not possible on some projects with strict security policies

**Comment by ghamaide** [comment]
@williamdclt @benja-M-1 @tcheymol I suggest we leave this issue open until at least a beta package of react-router-redux is delivered. Ok for you ? I can add the withRouter for the moment.

**Comment by benja-M-1** [comment]
closed in favor of #177
